datopian/frontend-v2

- themes/eds/i18n/da.json
- themes/eds/i18n/en.json
- themes/eds/public/stylesheets/app.css
- themes/eds/routes.js
- themes/eds/views/base.html
- themes/eds/views/collection.html
- themes/eds/views/collections-home.html
- themes/eds/views/home.html
- themes/eds/views/owner.html
- themes/eds/views/partials/data-search-form.njk
- themes/eds/views/partials/data-search-pagination.njk
- themes/eds/views/partials/data-search-results.njk
- themes/eds/views/partials/search-filter.njk
- themes/eds/views/search.html
- themes/eds/views/showcase.html
- views/static.html
Energidataservice frontend-v2 made to look like as it is on live.
Done according to: https://gitlab.com/datopian/eds/eds-pm/issues/93
> Eds new frontend

- README.md
- env.template
- index.js
- plugins/wp/cms.js
- plugins/wp/index.js
- routes/dms.js
- tests/lib/index.test.js
- tests/routes/index.test.js
Refactors Wordpress CMS backend as plugin.
> [CMS][m]: Refactor WP CMS backend as plugin

- README.md
- package.json
This PR adds a command to run the app in development with:
```
npm run dev
```
or 
```
yarn dev
```
I also documented it in the README. 
Addresses #46 although not fully since it doesn't update the guide.
> Add dev command

- utils/index.js
Found that while working on a theme: error stack trace was not displayed.
I reproduced the way plugin errors are displayed
https://github.com/datopian/frontend-v2/blob/dcbafc57e29980d36ee8047baf06e9239543e445/utils/index.js#L274
Before:
```
Loading configured theme...                                                                                                                   
ckan-ng-theme-xxx                                                                                                                           
WARNING: Failed to load theme -- ckan-ng-theme-xxx                                                                                          
Loading configured plugins... …
```
> [s]: display exception raised when loading theme

- routes/dms.js
Without this, opening an URL with a wrong owner like http://localhost:4000/foo/lidar-aerien-2015 instead of http://localhost:4000/ville-de-montreal/lidar-aerien-2015 loads indefinetly:
```
(node:1549) UnhandledPromiseRejectionWarning: #<Response>                                                                                     
(node:1549) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async functio
n without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)                                     
```
I reproduced the same pattern which can be found each time there is a call to an `async function`.
Now the `404 error` is displayed.
> [s]: wrap Model.getProfile in a try/catch block

- README.md
- config/index.js
- env.template
- plugins/wp/README.md
- plugins/wp/index.js
By default, your blog is at `/news` but you now able to change it via env var:
```
export WP_BLOG_PATH=/blog
```
and now your blog is at `/blog`.
I'm implementing this as it is required for OpenDataDK project and overriding CMS path in the theme doesn't look a great idea.
> Configurable WP blog path

- fixtures/index.js
I guess this needs no explanation, but in JS it's `use strict`, not `use string` :-)
> [s]: fix typo

- utils/index.js
This is needed so we could build queries like this:
```js
const usefulTags = await Model.search({'facet.field': '["tags"]', 'facet.limit': 1000, 'facet.mincount': 12, size: 0})
```
In order to get all the tags that have more than 12 related datasets, straight from Solr. The only alternative to this that I've found is the much slower get-everything approach plus something like `.filter((tag) => tag.count > 12)` on the final set.
Not a blocker for anything, but I would be glad to see it merged so I could patch my query accordingly.
> Add facet.mincount to Solr query

- config/index.js
- env.template
- index.js
Fixes #67 
I added new env variables, added them to the configuration and used them in express middleware.
Now the cookie is set to expire with the browser session by default:
> Add env variables for express session

- utils/index.js
Besides default values, this introduces the possibility to manually provide more custom search params for Solr:
- `fq` for custom generated raw filter queries
- `facet.field` for when more (or fewer) facet fields need to be present in the query
Examples (from a real project):
- `fq` filtering for datasets belonging to multiple groups, e.g. `groups:"k-12" groups:"student-loans"`
- `facet.field` for including a project specific facet, e.g. `['organization', 'groups', 'tags', 'res_format', 'license_id', 'level_of_data_string']`
> Add option to provide `fq` and `facet.field` for search

- index.js
E.g., I'm developing a theme and I want to use `lib/dms.js` and `utils/index.js` modules. So in my theme `my-theme/index.js` I can do:
```javascript
module.exports = function (app) {
const dms = app.get('dms')
const config = app.get('config')
const utils = app.get('utils')
// Then I can use these to do my dev work
}
```
> Expose 'lib' and 'utils' to themes and plugins

- themes/opendk/views/collections-home.html
- themes/opendk/views/partials/data-search-results.njk
- Applied colored in Data format of resources
- Duplicate data format removed 
- groups and organizations alphabetically sorted
> [opendk][s]: consolidate data format 

- themes/opendk/views/showcase.html
The template variable `owner.description ` contain HTML <a> tags and not closed on truncate. So, can't render plain text cuz it contain other tags also. So, for now it is fixed by simply replacing a tag with nothing
> Readmore link of organizations - opendk fixed

- plugins/ckan_pages/index.js
- Fixed Montreal not showing recent data issues
> [ckan_pages] plugin home controller override converted as middleware controller

- config/index.js
- index.js
* Ensure trailing slash for API Url
* If markdown render fails, return original string
> [fix][s]: Fix api url trailing slash

- themes/opendk/views/showcase.html
> fixed keywords typography

- themes/opendk/views/home.html
Resolves: 
Dates on blogposts on front page should be the same as on the blog page (showing the release date, not the last edited date).
> [fix][xs] fixes dates on front page blogposts

- themes/opendk/views/blog.html
- themes/opendk/views/home.html
Fixes 
```
Why is Events translated to Begivenheder in the category filter?
Could the category label be a linkt to the category eg, "Events" links to blog?category=events
```
from https://gitlab.com/datopian/ckan-next-gen/issues/121#final-round
> [fix][s] categories in blog page

- plugins/wp/cms.js
- plugins/wp/index.js
Using 2 separate requests if there is a parent, because WP API does not allow for a single one:
If to use [`posts/slug:%24post_slug/` method]( https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/slug:%24post_slug/) - we cannot specify parent id - only slug -> if we have two pages one with parent and another without the parent with the same slug - the one without the parent will be returned.
If to use [`posts/` method](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/) we cannot specify slug (they say in the documentation that it can be specified in tag or category, but that does not work in practice)
> [wp][s] fixes getting wp page with parent

- plugins/ckan_pages/index.js
Removed html tags when showing truncated content of news, because it opens tags without closing them and creates rendering problems and news.slug doesn't exist.
> [news][s]: news content html tags removed when showing lists

- fixtures/index.js
- plugins/ckan_pages/cms.js
- tests/plugins/ckan_pages.test.js
Add `getListOfPages` function to `ckan_pages` module.
Requirement for national grid.
Includes tests.
> [ckan_pages] getListOfPages - add fixtures + test

- fixtures/index.js
- lib/dms.js
- routes/dms.js
- tests/lib/index.test.js
- tests/routes/index.test.js
Sometimes flakiness in the API causes failures for this call which we should handle gracefully (degrade to empty profile obj)
> [dms] Catch bad getProfile call and return empty obj

- tests/utils/index.test.js
- utils/index.js
- The schema table supported.
- The schema property can be provided in DMS  using a `scheming` and `composite` extension on CKAN classic. 
```
{
...
revision_id: '392dfb53-17c4-45c3-a236-fc7c3b6ca0b9',
schema: {
fields: '[{"comment": "School name registered in education department", "description": "This is the school name ", "size": "12", "type": "string", "example": "Datopian School", "unit": "String", "name": "School Name"}]'
},
url_type: 'upload',
...
}
```
> Schema table support

- plugins/wp/cms.js
Adds the ability to create requests for WP API with this endpoint: https://github.com/Automattic/wpcom.js/blob/master/docs/wpcom.req.md, useful for example for getting [a list of files](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/media/) - as no other endpoint allows to do that (even [media](https://github.com/Automattic/wpcom.js/blob/master/docs/media.md)).
> [wp][s]: adds original WP API request endpoint

- lib/dms.js
- tests/utils/index.test.js
- utils/index.js
- fetched dictionary fields information using `dictionary fields` API.
- `ckanSchemaToTableSchema` utils added to convert CKAN dictionary fields to table schema.
> Data dictionary fields to table schema

- fixtures/index.js
- lib/dms.js
- tests/utils/index.test.js
- utils/index.js
Such as `_id`, `_full_text` and `_count`.
> Remove internally generated DataStore fields

- plugins/ckan_pages/index.js
@anuveyatsu 
As you can see here:
https://montreal.l3.ckan.io/api/3/action/ckanext_pages_list
or here:
https://montreal.l3.ckan.io/api/3/action/ckanext_pages_show?page=table-de-concertation-premiere-assemblee-pleniere-25-avril-2012
there is no `date` value, but `publish_date` value.
**Before changes**
**After changes**
> [fix][xs] Publish date not showing correct values

- routes/dms.js
Created a function that can be re-used/shared so that generated 'datapackage.json' is consistent.
We generate 'datapackage' object for showcase (dataset) page.
We also generate it for 'datapackage.json' api route (`/owner/dataset/datapackage.json`).
Problem is that these 2 objects aren't consistent, however, it should be.
So this PR includes a shared function so that both routes use it and 'datapackage' json is identical.
> Consistent 'datapackage' object

- tests/utils/index.test.js
- utils/index.js
By default CKAN `datastore_search` doesn't provide sorted dataset records. so, Adding query `sort=_id desc` on datastore search API  will provide  sorted with _id in descending order. 
On the table view of data explorer, recently updated data will appear in the first row.
>  Sorting query added on datastore search api url

- index.js
@anuveyatsu 
Please, would you review this PR.
This fixes configuring of Moment locale.
**Description**
Moment locale was not changing according to `defaultLocale` cookie value. Idea was to set Moment locale in `frontend-v2` itself, not from Theme, so this can be reused in all cases that needs translations. In this particular case we use `moment.fromNow()` function which returns human readable value from `datetime` value. Our starting point was:
```javascript
i18n.configure({
cookie: 'defaultLocale',
directory: __dirname + translationsDir,
locales: config.get('LOCALES') || ['en'],
defaultLocale: config.get('DEFAULT_LOCALE') || 'en'
})
// also set it up for moment:
moment.locale(i18n.getLocale())
```
**Implementation**
1. In this solution I didn't use `locales: config.get('LOCALES') || …
> [fix][s] Configure Moment locale based on i18n

- lib/dms.js
- tests/lib/index.test.js
- utils/index.js
-  Now `getOrganizations` DMS  supports users passed params such as .  `include_groups`,  `include_tags` etc..
- Default truncating description of organization removed from dms . It can be implemented on a theme.
> getOrganizations additional params support

- utils/index.js
In case a query has `fq` param don't forget to include it.
> [search][s]: fixes dms search fq param

- config/index.js
When trying to launch app without `SITE_URL` set up (worked previously) there is an error:
```
Cannot read property 'replace' of undefined
at Object.<anonymous> (/Users/evgeniyavakarina/Documents/upwork/datopian/frontend-v2/config/index.js:21:34)
```
This PR is a fix for it
> [env][xs]: fixes property 'replace' of undefined site url error

- routes/dms.js
@anuveyatsu Please can you review this?
This solves https://gitlab.com/datopian/core/support/-/issues/250
There are cases when JSON/XML resources are external - linked ones. In those cases we don't need redirection. Example:
1. Dataset: https://donnees.montreal.ca/ville-de-montreal/contrats-et-subventions-api
2. External resource: http://ville.montreal.qc.ca/vuesurlescontrats/api/
With these changes we first check is there a redirection, and if yes we change the resource URL to `res.headers.location`. If there is not redirection the URL of the resource remains the same.
> [fix][xs] Fix text view case without redirection

- index.js
There was no  `/robots.txt`. When the crawler doesn't find `robots.txt` the next matched  `/:organization` route throws a 404 error.  So, adding `robots.txt ` as a middleware function. For now, it is allowing all paths.
> Robots txt added

- routes/dms.js
- utils/logger.js
The major issue with the current error logger is that it doesn't properly log full stack trace which is essential for debugging. This PR fixes it.
It also fixes a small bug when rendering a dataset page without `resource.views`.
> Include stack trace of an error if exists + small bug fix

- lib/dms.js
Before when the resource URL is invalid it just displays the blank content instead of displaying 404. Now it is fixed this PR.
> Redirect to 404 page if resource don't exist. 

- index.js
- routes/dms.js
I think ` PAGE NOT FOUND` is more relevant than the `requested URL  not found`.
> error message improved , page not found instead of url not found

- lib/dms.js
In some projects, we need to differentiate frontend API requests on the admin site so, for that adding a custom header.
> Custom header added to differentiate frontend API request.

- package.json
- routes/auth/authHandler.js
- routes/auth/errorHandler.js
- routes/auth/index.js
- yarn.lock
Since we have updated the Kratos  SSO server to 0.5.5-alpha we also need to update the client side as well. This PR incorporates all the required changes. 
**Note:** require to update callback URL on Oauth app provider eg.  `http://127.0.0.1:4000/self-service/methods/oidc/callback/github`
**Also**  `@oryd/kratos-client` deprecated and moved to   `@ory/kratos-client`
> Package kratos client updated for  SSO 

- lib/dms.js
DMS module runs in Nodejs (backend) and makes lots of requests to CKAN API using public URL which means all those requests are going through NGINX. In some situations it is being blocked depending on proxy configs, e.g., there might be limit on number of concurrent connections from a given IP or number of connections per second.
To improve this, we want to make requests from node app to CKAN API within the private network.
There are other places where frontend does connect to CKAN API (e.g., in custom themes developers don't always use this DMS library but they write custom code). But this DMS module makes 90% of requests, it also does a lot of concurrent requests where a package has lots of resources.
> Connect to CKAN API via private network from frontend server.

- plugins/wp/index.js
Don't break a site when the frontend is unable to fetch WordPress home content.  
Not related to this PR but  I can issue it always looking for post number 3 so, probably it was implemented for a specific project.  I think we should use slug name eg 'home' instead of post number but need to confirm if it is already used on other projects.
> Handled error with try catch on homepage wordpress content

- .github/workflows/action.yml
This enables us to deploy the frontend service using the latest Node version.
> CI/CD: run tests using node v14 and v16 as well.
