datopian/frontend-v2

- routes/dms.js
Fixes https://gitlab.com/datopian/ckan-next-gen/issues/8
> [dms][xs]: Replace single quotes in data json for previews

- themes/eds/views/base.html
- themes/eds/views/showcase.html
Added google analytics to EDS theme as it is already implemented in default theme.
> [showcase,base][m]: added google analytics to eds theme

- themes/eds/views/collections-home.html
Update made per: https://gitlab.com/datopian/eds/eds-pm/issues/107.
> [collections-home][xs]: updated organizations link

- index.js
- plugins/example/index.js
- plugins/example/views/example.html
This shows how we can load views from plugins. Needed for dashboard plugin, and useful moving forward. 
Related to https://gitlab.com/datopian/ckan-next-gen/issues/17
> [plugins][s]: Example of loading view via plugin

- routes/dms.js
Add display items array containing initialization object for rendering
data-explorer per resource
> [data-explorer][s]: Add displayItems array per resource

- routes/dms.js
- views/base.html
- views/showcase.html
* `dataExplorers` property views have objects for table, chart and map.
* also includes path fixes for loading build files from datapackage-views-js
> Data Explorer fixes

- plugins/carto/views/map-page.html
PR created per https://gitlab.com/datopian/ckan-next-gen/issues/103
> [carto][s]: map page design

- themes/opendk/views/base.html
-  the content update and icons added
> [opendk][s]: footer content update with icons

- index.js
- plugins/wp/index.js
- routes/dms.js
- controller execution flow re-arranged 
- wp home controller as a middleware updated.
- core controller update.
> WP plugin override home route controller fixed

- routes/dms.js
- themes/opendk/index.js
- themes/opendk/views/home.html
- Middleware controller added on the home route.
- Home template updated. 
- ATM it is not random, just limit with 4 items. Still figuring out how we can render the random object.
> [WIP]ODDK theme middleware controller added for group features on home page

- themes/opendk/views/home.html
When you start typing in the search field on the homepage you get two options in dropdown, one executes the query on the list of datasets and the other on content.
> [search-field][m]: search field double link

- themes/opendk/views/home.html
Keyboard support implemented for home page search dropdown.
> Home page search

- themes/opendk/views/base.html
- themes/opendk/views/home.html
Search dropdown added to navigation bar by using jQuery library.
> [search-dropdown][l]: search dropdown added to navigation bar

- themes/opendk/views/base.html
> OODK Footer right aligned 

- themes/opendk/views/showcase.html
>  missing tags added as keyword on oddk  dataset page

- themes/opendk/views/showcase.html
- Just font size reduced for now.
Old
new
> reduced filename font size

- themes/opendk/views/showcase.html
> preview button added

- themes/opendk/views/blog.html
> [WIP] preview text displayed on blog page

- fixtures/index.js
- package.json
- routes/dms.js
- tests/utils/index.test.js
- utils/index.js
- views/partials/resource-display.njk
- views/partials/resource-summary.njk
- views/showcase.html
- yarn.lock
Generally, removing auto-generation of views in frontend - it is managed from CKAN Classic backend instead.
* Refactoring data package preparation process.
* Modularized all operations in utils.
* Removed auto-generation of views/dataexplorers.
* refactored templates to work with 'displayResources' attribute.
* also, made fixes in utils functions.
* preparing data explorer widgets for display
> Showcase controller/template refactoring

- plugins/applications-showcase/views/application-showcases.html
Updated showcase view requested by: https://gitlab.com/datopian/clients/ckan-montreal/issues/52
> [showcase view][m]: change showcases so it's consistent with categories

- routes/dms.js
- utils/index.js
This PR allows devs to have predefined `datapackage` object.
> Extending showcase route

- lib/dms.js
Candidate for backport to main branch
Resolves a peculiar bug with the CKAN service - intermittent 500 on fetch package via POST
> [dms] Use GET for getPackage

- fixtures/index.js
- package.json
- plugins/google-analytics/api.js
- plugins/google-analytics/index.js
- tests/plugins/google-analytics.test.js
- yarn.lock
Adds google analytics connection settings according to the doc: http://tech.datopian.com/frontend/plugins/#google-analytics
> [plugin][m]: updates google-analytics plugin

- Dockerfile
Hey there :)
While the recommended way worked (`yarn dev` on my host machine), I tried to setup the datopian frontend with docker., too.
I had to do some "fixes", to make it work for me locally, though I am not sure if I am breaking anything else as I removed nodemon altogether and I have to admit I was not entirely sure what it does.
Do you use the datopian-frontend with docker anyways? Maybe you can verify if my changes make sense or if I was missing something else.
Thank you, other than that it works like a charm :)
> Docker container

- routes/dms.js
@anuveyatsu Please, can you review this?
This fixes reopened issue https://gitlab.com/datopian/core/support/-/issues/249#note_403404895.
Some of the resources, for which we are fetching data for the text view, are externally linked over `HTTP`. With this change, we first check the protocol, and after that fetch data over that protocol (`HTTP` or `HTTPS`)
> [fix][xs] Fixing external resources fetching over unsecured connection

- routes/dms.js
- utils/index.js
@anuveyatsu 
Please, can you review this?
This fixes https://gitlab.com/datopian/core/support/-/issues/251#note_406719012
On ODDK backend there are externally linked resources with missing URLs. This breaks `text view` feature functionality and dataset (showcase) page loading with the error message `Something failed. Please, try again later.` These changes capture such resources and override their processing.
After these changes, the pages are loading well.
> Fix missing resource URL/path breaks frontend showcase page loading

- env.template
- index.js
- lib/dms.js
- package.json
- routes/auth/authHandler.js
- routes/auth/errorHandler.js
- routes/auth/index.js
- routes/dms.js
- utils/index.js
- utils/logger.js
Related Issue: https://github.com/datopian/frontend-v2/issues/182
Now we have more control over the logging level.  Just need to add log level   `LOG_LEVEL` on the env file. 
We also need to change it on the theme and also on the plugin for the consistent logging.
**logging screenshot**
> Replaced logging with winston log

- index.js
- routes/dms.js
@anuveyatsu Please can you review this. This is URGENT to be implemented so we can apply this to stop the Bots on Montreal frontend.
I added that if we have robots.txt configured in theme /public folder to use it. In oposite we will use default `User Agent: *` `Allow: /`
> [add][xs] Added robots.txt from theme /public folder

- lib/dms.js
Added custom user agent on the header as `frontend-v2/latest (internal API call from frontend app)` so that we can differentiate/identify the request source.
> [api][xs]: Custom user agent added on API request header

- index.js
The date parameter will be the UTC format so, it should be compared again UTC format.
> Bug fixed utc date formatting

- utils/index.js
Datapackage objects can grow significantly depending on number of resources, schema etc. In some situations it may lead to taking up too much memory so we don't want to make unnecessary copies of such objects.
> Avoid making copies of objects where it is unnecessary.

- index.js
- lib/dms.js
- package.json
- yarn.lock
- Improve logging 
- Add Error logs and handle exceptions to log the exception
The sample logging for the request will be similar to the apache logging structure.
```
35.240.151.105 - - [11/Jan/2022:12:48:20 +0000] "GET / HTTP/1.1" 200 36543 "-" "GoogleStackdriverMonitoring-UptimeChecks(https://cloud.google.com/monitoring)"
```
> Improvement in logging and error handling

- .github/workflows/action.yml
- fixtures/index.js
- package.json
- plugins/google-analytics/api.js
- tests/plugins/google-analytics.test.js
- yarn.lock
- upgraded googleapis latest package
- Implemented GA4 analyticsdata API func.
> GA plugin updated to support GA4 analytics report
